//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TommAPI.Resources.Controllers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountController {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountController() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TommAPI.Resources.Controllers.AccountController", typeof(AccountController).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmark successed..
        /// </summary>
        public static string BookMark {
            get {
                return ResourceManager.GetString("BookMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bootcamp  job updated successfully..
        /// </summary>
        public static string BootcampUpdateSuccess {
            get {
                return ResourceManager.GetString("BootcampUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your old password is incorrect..
        /// </summary>
        public static string ChangePassFaild {
            get {
                return ResourceManager.GetString("ChangePassFaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Christmas job updated successfully..
        /// </summary>
        public static string ChritmasUpdateSuccess {
            get {
                return ResourceManager.GetString("ChritmasUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Email Id or Username is already registered. Please try another..
        /// </summary>
        public static string EmailAlready {
            get {
                return ResourceManager.GetString("EmailAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Email Id is not registered with us. Please try again..
        /// </summary>
        public static string EmailNotFound {
            get {
                return ResourceManager.GetString("EmailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Username or Password. Please try again..
        /// </summary>
        public static string EmailPassNotMatch {
            get {
                return ResourceManager.GetString("EmailPassNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please contact administrator..
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus day is now set to .
        /// </summary>
        public static string FocusDaySuccess {
            get {
                return ResourceManager.GetString("FocusDaySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Email Id  is not registered with us or Reset Code is invalid. Please try again..
        /// </summary>
        public static string Forgotpassfailed {
            get {
                return ResourceManager.GetString("Forgotpassfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password for TeamTOM App!.
        /// </summary>
        public static string ForgotPasswordSubject {
            get {
                return ResourceManager.GetString("ForgotPasswordSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday can not be marked for future date.
        /// </summary>
        public static string FutureDateHolidayCantbeMarked {
            get {
                return ResourceManager.GetString("FutureDateHolidayCantbeMarked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday mode turned off successfully..
        /// </summary>
        public static string HolidayTurnedOffMsg {
            get {
                return ResourceManager.GetString("HolidayTurnedOffMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday mode turned on successfully..
        /// </summary>
        public static string HolidayTurnedOnMsg {
            get {
                return ResourceManager.GetString("HolidayTurnedOnMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your Email Id or Username..
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are now logged in..
        /// </summary>
        public static string LoginSuccess {
            get {
                return ResourceManager.GetString("LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apologies, our automated email servers are currently experiencing a technical fault. Please message the TeamTOM help desk support@theorganisedmum.blog to help reset your password for you..
        /// </summary>
        public static string MailError {
            get {
                return ResourceManager.GetString("MailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User holiday deleted successfully..
        /// </summary>
        public static string MigrateDataSuccess {
            get {
                return ResourceManager.GetString("MigrateDataSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data from old app could not be synced up. Please try again later..
        /// </summary>
        public static string MigrateErrorData {
            get {
                return ResourceManager.GetString("MigrateErrorData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Tasks Found..
        /// </summary>
        public static string NoRecord {
            get {
                return ResourceManager.GetString("NoRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Record Found..
        /// </summary>
        public static string NoRecordFound {
            get {
                return ResourceManager.GetString("NoRecordFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Notes have been updated..
        /// </summary>
        public static string NoteSuccess {
            get {
                return ResourceManager.GetString("NoteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Email Id or Username is already registered. Please try another..
        /// </summary>
        public static string NotExist {
            get {
                return ResourceManager.GetString("NotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password should be different from your old password. Please try again..
        /// </summary>
        public static string OldNewPassSame {
            get {
                return ResourceManager.GetString("OldNewPassSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Password has been updated..
        /// </summary>
        public static string PassUpdate {
            get {
                return ResourceManager.GetString("PassUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Password has been changed successfully.
        /// </summary>
        public static string PassUpdateSuccess {
            get {
                return ResourceManager.GetString("PassUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patreon categories updated successfully..
        /// </summary>
        public static string PatreonCategory {
            get {
                return ResourceManager.GetString("PatreonCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patreon email updated successfully..
        /// </summary>
        public static string PatreonEmail {
            get {
                return ResourceManager.GetString("PatreonEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patreon email already associated to other email..
        /// </summary>
        public static string PatreonEmailExist {
            get {
                return ResourceManager.GetString("PatreonEmailExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Tasks have been restored successfully..
        /// </summary>
        public static string Refresdaytask {
            get {
                return ResourceManager.GetString("Refresdaytask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there appears to be a problem registering you, please try again..
        /// </summary>
        public static string RegisterFailed {
            get {
                return ResourceManager.GetString("RegisterFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thankyou! You registration is successful. .
        /// </summary>
        public static string Registersuccess {
            get {
                return ResourceManager.GetString("Registersuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations, you are now registered with the TeamTOM App!.
        /// </summary>
        public static string RegisterTommApp {
            get {
                return ResourceManager.GetString("RegisterTommApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeamTOM App Password Reset.
        /// </summary>
        public static string ResetPasswordSubject {
            get {
                return ResourceManager.GetString("ResetPasswordSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task day Restore successfully..
        /// </summary>
        public static string RestoreDay {
            get {
                return ResourceManager.GetString("RestoreDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User childrens added successfully..
        /// </summary>
        public static string SaveChildrens {
            get {
                return ResourceManager.GetString("SaveChildrens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get playlist.
        /// </summary>
        public static string SpotifyTokenFailed {
            get {
                return ResourceManager.GetString("SpotifyTokenFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success..
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have enter invalid token..
        /// </summary>
        public static string TokenExpire {
            get {
                return ResourceManager.GetString("TokenExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Token to reset the password has been sent to the registered Email Id..
        /// </summary>
        public static string TokenSent {
            get {
                return ResourceManager.GetString("TokenSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token to reset the password has been sent to the registered Email Id..
        /// </summary>
        public static string TokenSentAdmin {
            get {
                return ResourceManager.GetString("TokenSentAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task day updated successfully..
        /// </summary>
        public static string UpdatedayTaskJob {
            get {
                return ResourceManager.GetString("UpdatedayTaskJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post audio url updated successfully..
        /// </summary>
        public static string UpdatePost {
            get {
                return ResourceManager.GetString("UpdatePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job has been rolled over..
        /// </summary>
        public static string UpdateRolloverday {
            get {
                return ResourceManager.GetString("UpdateRolloverday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post data updated successfully.
        /// </summary>
        public static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap completed successfully..
        /// </summary>
        public static string UpdateSwapJobday {
            get {
                return ResourceManager.GetString("UpdateSwapJobday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task job updated successfully..
        /// </summary>
        public static string UpdateTaskJob {
            get {
                return ResourceManager.GetString("UpdateTaskJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User profile updated successfully..
        /// </summary>
        public static string UserAdminSuccess {
            get {
                return ResourceManager.GetString("UserAdminSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Username has been sent to the registered Email Id..
        /// </summary>
        public static string UsernameSent {
            get {
                return ResourceManager.GetString("UsernameSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeamTOM App - Username request.
        /// </summary>
        public static string UsernameSubject {
            get {
                return ResourceManager.GetString("UsernameSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Username or Password. Please try again..
        /// </summary>
        public static string UserPassNotMatch {
            get {
                return ResourceManager.GetString("UserPassNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User profile update successfully..
        /// </summary>
        public static string UserUpdateSuccess {
            get {
                return ResourceManager.GetString("UserUpdateSuccess", resourceCulture);
            }
        }
    }
}
